"""empty message

Revision ID: 2ce67934c2e1
Revises: 488c0fb4500d
Create Date: 2025-05-01 14:56:58.645608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce67934c2e1'
down_revision = '488c0fb4500d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist_Music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('music', sa.String(length=120), nullable=False))
        batch_op.drop_column('music_id')

    with op.batch_alter_table('Venue_Music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('music', sa.String(length=120), nullable=False))
        batch_op.drop_column('music_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue_Music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('music_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('music')

    with op.batch_alter_table('Artist_Music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('music_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('music')

    # ### end Alembic commands ###
