"""add cascade delete to Show foreign keys

Revision ID: ca59255c2a60
Revises: c4f64c4c3b3e
Create Date: 2025-09-05 16:34:30.714635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca59255c2a60'
down_revision = 'c4f64c4c3b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.drop_constraint('Show_venue_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('Show_artist_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Venue', ['venue_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'Artist', ['artist_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Show_artist_id_fkey', 'Artist', ['artist_id'], ['id'])
        batch_op.create_foreign_key('Show_venue_id_fkey', 'Venue', ['venue_id'], ['id'])

    # ### end Alembic commands ###
